---
instance_name: "인스턴스 이름을 입력하세요."
machine_type: "머신 타입을 입력하세요."
region: "Region을 입력하세요."
zone: "Zone을 입력하세요."
project: "프로젝트를 입력하세요."
auth_kind: "auth kind를 입력하세요."
#ComputeEngine > Storage > images > search > selfLink
source_image: projects/confidential-vm-images/global/images/ubuntu-1804-bionic-v20201014
prefix_name: "prefix 이름을 입력하세요."
disk_size: 10