---
- name: Host Info Facts
  command: "{{ command }}"
  register: host_info

- name: Print Host Name
  debug:
    msg: "hostName is {{ host_info.stdout }}"

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx
  service:
    name: nginx
    state: started
